export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST"
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS"
export const GET_BOOKINGS_ERROR = "GET_BOOKINGS_ERROR"

export const CLEAR_BOOKINGS_ERRORS ="CLEAR_BOOKINGS_ERRORS"