export const FETCH_ALL_SALOONS_REQUEST = "FETCH_ALL_SALOONS_REQUEST"
export const FETCH_ALL_SALOONS_SUCCESS = "FETCH_ALL_SALOONS_SUCCESS"
export const FETCH_ALL_SALOONS_ERROR = "FETCH_ALL_SALOONS_ERROR"

export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR"